# Generated by Django 4.0.2 on 2022-02-27 08:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='age_group',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('10s', '10s'), ('20s', '20s'), ('30s', '30s'), ('40s', '40s'), ('50s', '50s')], max_length=5), blank=True, default=list, size=5),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=3),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='yo', max_length=5),
            preserve_default=False,
        ),
    ]
