FROM python:3.9

ENV PYTHONUNBUFFERED 1

WORKDIR /drf_src/

COPY . .

RUN pip install -r requirements.txt

VOLUME /drf_src/

EXPOSE 8080

CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000

ENV ENV=local